services:
  server_core:
    build:
      context: .
      dockerfile: ./server_core/Dockerfile
    image: roadmap_angular_image
    pull_policy: never 
    container_name: roadmap_angular_server
    user: "1000:1000"
    ports:
      - "4200:4200"
    volumes:
      - ../.:/var/www/html
    working_dir: /var/www/html
    tty: true
    stdin_open: true
    networks:
      - roadmap_angular_network

networks:
  roadmap_angular_network:
    name: roadmap_angular_network
